import { Mail } from 'lucide-react'
import { useState } from 'react'
import { FaFacebookF, FaInstagram, FaWhatsapp } from 'react-icons/fa'

function Footer({ footerLinks, copyright, onNavigate }) {
  const [subscribed, setSubscribed] = useState(false)

  return <footer className="bg-[#f0ede5] px-5 py-12 text-[#18312f] sm:px-8 lg:px-12 lg:py-16"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[1.3fr_2fr]"><div><button className="font-display text-3xl font-semibold" onClick={() => onNavigate('Home')} type="button">roamwell<span className="text-[#da6b47]">.</span></button><p className="mt-5 max-w-xs text-sm leading-6 text-[#58706a]">Go farther, stay longer, and come home with a better story.</p><div className="mt-7 flex gap-3"><a aria-label="Instagram" className="social-icon rounded-full border border-[#aebcb4] p-2.5" href="https://www.instagram.com/" rel="noreferrer" target="_blank"><FaInstagram size={17} /></a><a aria-label="Facebook" className="social-icon rounded-full border border-[#aebcb4] p-2.5" href="https://www.facebook.com/" rel="noreferrer" target="_blank"><FaFacebookF size={17} /></a><a aria-label="WhatsApp" className="social-icon rounded-full border border-[#aebcb4] p-2.5" href="https://wa.me/921111762693" rel="noreferrer" target="_blank"><FaWhatsapp size={17} /></a><button aria-label="Email us" className="social-icon rounded-full border border-[#aebcb4] p-2.5" onClick={() => onNavigate('Contact us')} type="button"><Mail size={17} /></button></div></div><div className="grid grid-cols-2 gap-8 sm:grid-cols-3">{footerLinks.map((group) => <div key={group.heading}><h3 className="mb-4 text-xs font-bold uppercase tracking-[0.18em] text-[#da6b47]">{group.heading}</h3><ul className="space-y-3">{group.links.map((link) => <li key={link}><button className="footer-link text-left text-sm text-[#58706a] hover:text-[#18312f]" onClick={() => onNavigate(link)} type="button">{link}</button></li>)}</ul></div>)}</div></div><div className="mx-auto mt-12 max-w-7xl rounded-[4px] bg-[#d9e6dd] p-5 sm:flex sm:items-center sm:justify-between sm:gap-8"><div><h2 className="font-display text-2xl">A little inspiration, occasionally.</h2><p className="mt-1 text-sm text-[#58706a]">New journeys and field notes, sent with care.</p></div>{subscribed ? <p className="mt-4 text-sm font-bold text-[#18312f] sm:mt-0">You are on the list. Welcome aboard.</p> : <form className="mt-4 flex max-w-md gap-2 sm:mt-0" onSubmit={(event) => { event.preventDefault(); setSubscribed(true) }}><label className="sr-only" htmlFor="newsletter-email">Email address</label><input className="booking-input mt-0" id="newsletter-email" name="newsletterEmail" placeholder="Email address" required type="email" /><button className="rounded-full bg-[#18312f] px-4 py-2 text-sm font-bold text-white" type="submit">Subscribe</button></form>}</div><div className="mx-auto mt-12 max-w-7xl border-t border-[#cbd4ce] pt-5 text-xs text-[#58706a]"><p>{copyright}</p></div></footer>
}
export default Footer
