import { ArrowLeft, ArrowRight, Mail, MessageCircle } from 'lucide-react'
import { useState } from 'react'

const topicContent = {
  journal: { eyebrow: 'The Roamwell journal', title: 'Notes from the road.', intro: 'Stories, field notes, and useful little discoveries from the people who make Roamwell.', sections: [['A slower way to see a city', 'The best journeys leave a little space around the itinerary. We share our favorite neighborhoods, local tables, and unplanned turns.'], ['Meet the people behind the places', 'Our guides introduce the artists, cooks, historians, and hosts who give each destination its character.']] },
  story: { eyebrow: 'About Roamwell', title: 'Travel with more feeling.', intro: 'Roamwell began with a simple belief: the places we visit should change the way we see the world.', sections: [['Small by design', 'We keep groups small so conversations can run longer, local businesses can benefit, and every day can feel personal.'], ['Curious, always', 'Our team searches for the overlooked details that turn a good trip into a story worth telling.']] },
  guides: { eyebrow: 'Our people', title: 'Meet your guides.', intro: 'Warm, deeply curious locals who know when to lead the way and when to step aside.', sections: [['Local knowledge, generously shared', 'Every guide brings lived experience, trusted relationships, and a genuine affection for their home.'], ['A human pace', 'Our guides help you find the balance between seeing it all and being fully present.']] },
  contact: { eyebrow: 'We are here to help', title: 'Let’s plan something wonderful.', intro: 'Tell us where your curiosity is taking you. A Roamwell travel designer will reply within one business day.', sections: [['Email', 'hello@roamwell.example'], ['Phone', '+92 21 111 ROAMWELL', 'Monday to Friday, 9:00 to 18:00 PKT']] },
  faqs: { eyebrow: 'Good to know', title: 'Questions, answered.', intro: 'A few helpful details before you set off.', sections: [['What is included?', 'Your accommodation, local experiences, selected meals, and an expert guide are included in every journey.'], ['Can I customize a trip?', 'Absolutely. Contact our team and we will shape the pace, dates, and details around you.']] },
  insurance: { eyebrow: 'Travel with confidence', title: 'Protection for the unexpected.', intro: 'We recommend comprehensive travel insurance for every journey.', sections: [['What to look for', 'Choose cover for medical emergencies, cancellation, baggage, and activities included in your itinerary.'], ['Need help choosing?', 'Our team can explain what your journey involves, but your insurance provider will confirm the right policy.']] },
  private: { eyebrow: 'Made for you', title: 'Private trips, your way.', intro: 'A completely personal route for families, friends, and curious groups.', sections: [['Your rhythm', 'Choose the dates, pace, and people you want beside you. Our experts will build the rest.'], ['Your world', 'From a private cooking table to a quiet mountain lodge, we open doors that fit your story.']] },
  gift: { eyebrow: 'Give a story', title: 'A journey is a beautiful gift.', intro: 'Send someone special somewhere they have always wanted to go.', sections: [['Simple to give', 'Choose a gift amount or speak with our team about a specific journey. We will make the surprise easy.'], ['Made to remember', 'Every gift arrives with a personal note and room for the recipient to make it their own.']] },
  all: { eyebrow: 'Explore Roamwell', title: 'There is a whole world waiting.', intro: 'Browse every handpicked journey and find the place that keeps calling your name.', sections: [['Start wandering', 'Explore our full collection of journeys across cities, coastlines, mountains, and deserts.']] },
}

function TopicPage({ topic, onBack, onContact }) {
  const content = topicContent[topic] || topicContent.journal
  const [messageSent, setMessageSent] = useState(false)

  return <main className="min-h-screen bg-[#f8f5ef] px-5 pb-20 pt-32 text-[#18312f] sm:px-8 lg:px-12"><div className="mx-auto max-w-5xl"><button className="mb-14 flex items-center gap-2 text-sm font-bold text-[#58706a] transition-colors hover:text-[#da6b47]" onClick={onBack} type="button"><ArrowLeft size={17} /> Back to home</button><div className="max-w-3xl"><p className="mb-4 text-xs font-bold uppercase tracking-[0.22em] text-[#da6b47]">{content.eyebrow}</p><h1 className="font-display text-5xl leading-[1.02] sm:text-7xl">{content.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#58706a]">{content.intro}</p></div><div className="mt-16 grid gap-5 border-t border-[#cbd4ce] pt-8 sm:grid-cols-2">{content.sections.map(([heading, text, detail]) => <article className="border-b border-[#cbd4ce] pb-8" key={heading}><h2 className="font-display text-3xl">{heading}</h2><p className="mt-3 text-base leading-7 text-[#58706a]">{text}</p>{detail && <p className="mt-2 text-sm font-bold text-[#da6b47]">{detail}</p>}</article>)}</div>{topic === 'contact' && <>{messageSent ? <p className="mt-10 rounded-[4px] bg-[#d9e6dd] p-4 text-sm font-bold">Thanks, your message has been sent. We will be in touch soon.</p> : <form className="mt-10 grid gap-4 rounded-[4px] bg-white p-6 shadow-sm sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); setMessageSent(true) }}><h2 className="font-display text-3xl sm:col-span-2">Send us a message.</h2><input className="booking-input" name="name" placeholder="Your name" required /><input className="booking-input" name="email" placeholder="Email address" required type="email" /><textarea className="booking-input min-h-32 sm:col-span-2" name="message" placeholder="How can we help?" required /><button className="w-fit rounded-full bg-[#da6b47] px-5 py-3 text-sm font-bold sm:col-span-2" type="submit">Send message</button></form>}</>}<div className="mt-16 flex flex-wrap gap-4"><button className="flex items-center gap-2 rounded-full bg-[#da6b47] px-5 py-3 text-sm font-bold" onClick={() => topic === 'contact' ? document.querySelector('form')?.scrollIntoView({ behavior: 'smooth' }) : onContact()} type="button"><Mail size={16} /> Email our team</button><button className="flex items-center gap-2 rounded-full border border-[#aebcb4] px-5 py-3 text-sm font-bold" onClick={onBack} type="button"><MessageCircle size={16} /> Start exploring <ArrowRight size={16} /></button></div></div></main>
}

export default TopicPage
